// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcG754qcTGDU2-8lNPMEtMudZa6VhFVeM',
    appId: '1:752613191889:web:e3fd39a226189c1b6015f0',
    messagingSenderId: '752613191889',
    projectId: 'snagsnapperpro',
    authDomain: 'snagsnapperpro.firebaseapp.com',
    storageBucket: 'snagsnapperpro.firebasestorage.app',
    measurementId: 'G-5KQKLMVRQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBllI-VE9Zs-brZu_Hp7CjkuR3xq6hIbBc',
    appId: '1:752613191889:android:96a5ae97bdf562676015f0',
    messagingSenderId: '752613191889',
    projectId: 'snagsnapperpro',
    storageBucket: 'snagsnapperpro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YuXDgrh8bJeF0m0CzCfotu0MUscHgQk',
    appId: '1:752613191889:ios:b41cf90e8c75c4ad6015f0',
    messagingSenderId: '752613191889',
    projectId: 'snagsnapperpro',
    storageBucket: 'snagsnapperpro.firebasestorage.app',
    androidClientId: '752613191889-n5bklm4cl92irclnmscac0fc4cf9l274.apps.googleusercontent.com',
    iosClientId: '752613191889-9ir7991g9edtl69hviacf2k4rag9heou.apps.googleusercontent.com',
    iosBundleId: 'uk.co.productiveapps.snagsnapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0YuXDgrh8bJeF0m0CzCfotu0MUscHgQk',
    appId: '1:752613191889:ios:b41cf90e8c75c4ad6015f0',
    messagingSenderId: '752613191889',
    projectId: 'snagsnapperpro',
    storageBucket: 'snagsnapperpro.firebasestorage.app',
    androidClientId: '752613191889-qeguuktpan1hskvg46orkhd1561mfjnj.apps.googleusercontent.com',
    iosClientId: '752613191889-9ir7991g9edtl69hviacf2k4rag9heou.apps.googleusercontent.com',
    iosBundleId: 'uk.co.productiveapps.snagsnapper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcG754qcTGDU2-8lNPMEtMudZa6VhFVeM',
    appId: '1:752613191889:web:fcf01a2cfba8e27a6015f0',
    messagingSenderId: '752613191889',
    projectId: 'snagsnapperpro',
    authDomain: 'snagsnapperpro.firebaseapp.com',
    storageBucket: 'snagsnapperpro.firebasestorage.app',
    measurementId: 'G-S98Z8QE4WP',
  );

}