// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCopmvO1hyy2hsk_Xigse6geSXcTFQ2k3w',
    appId: '1:567752366185:web:7042b05cb24997d49aeaf8',
    messagingSenderId: '567752366185',
    projectId: 'snag-snapper',
    authDomain: 'snag-snapper.firebaseapp.com',
    storageBucket: 'snag-snapper.appspot.com',
    measurementId: 'G-CL4DYHH1XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKiUIjP5pIEpJxVleM_ifILE0c6ijhHZQ',
    appId: '1:567752366185:android:1b999537e42d52369aeaf8',
    messagingSenderId: '567752366185',
    projectId: 'snag-snapper',
    storageBucket: 'snag-snapper.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH908ODozlKWl_hPofSzF1UU1ZBYbwEAU',
    appId: '1:567752366185:ios:ff31862b29a3bac49aeaf8',
    messagingSenderId: '567752366185',
    projectId: 'snag-snapper',
    storageBucket: 'snag-snapper.appspot.com',
    iosBundleId: 'com.productiveapps.snagsnapper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH908ODozlKWl_hPofSzF1UU1ZBYbwEAU',
    appId: '1:567752366185:ios:74c57f02c2ec1b989aeaf8',
    messagingSenderId: '567752366185',
    projectId: 'snag-snapper',
    storageBucket: 'snag-snapper.appspot.com',
    iosBundleId: 'com.productiveapps.snagsnapper.snagsnapper.RunnerTests',
  );
}
